spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: customer    
  datasource:
    url: jdbc:h2:mem:customerinformationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      customerUpdated: CUSTOMER_UPDATED_TOPIC
logging:  level:    root: INFO 