spring:
  application:
    name: spring-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shri73/Customer-Info
          search-paths: config-files/
server:
  port: 8888
