spring:
  kafka:
    consumer:
      group-id: ms_mail_consumer
    bootstrap-servers: localhost:9092
    topic:
      customerUpdated: CUSTOMER_UPDATED_TOPIC    
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:customerinformationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: USERNAME
    password: PASSWORD
    properties.mail.smtp:
      auth: true
      starttls.enable: true
security:
  basic:
    enabled: false
